# Generated by Django 6.0.1 on 2026-03-09 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_task_identity_type'),
        ('notification', '0004_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_type', to='base.state'),
        ),
    ]
