# Generated by Django 6.0.1 on 2026-03-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_task_identity_type'),
        ('notification', '0007_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_state', to='base.state'),
        ),
    ]
