# Generated by Django 6.0.1 on 2026-02-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_identity',
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
