# Generated by Django 6.0.1 on 2026-02-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('task', '0003_remove_task_task_identity_alter_task_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task_identity_type',
        ),
    ]
